sudo: required
dist: trusty
language: cpp
compiler: gcc
os: linux

before_install:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo -E apt-get -yq update &>> ~/apt-get-update.log
  - sudo bash travis.sh
install:
  - echo $(pwd)
  - mkdir build
  - cd build
  - cmake ../
  - make
  - find . -name testing
script:
  - ./test/testing
