sudo: required
dist: trusty
language: cpp
compiler: gcc
os: linux

before_install:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo -E apt-get -yq update &>> ~/apt-get-update.log
  - sudo ./travis.sh	
install:
  - mkdir build
  - cd build
  - cmake ../
  - make
script:
  - make test
