sudo: required
dist: trusty
language: cpp
compiler: gcc
os: linux

before_install:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo -E apt-get -yq update &>> ~/apt-get-update.log
  - sudo apt-get intall https://github.com/open-source-parsers/jsoncpp.git
install:
  - mkdir build
  - cd build
  - cmake ../
  - make

script:
  - make test
