set(vtkDICOMParser_LOADED 1)
set(vtkDICOMParser_DEPENDS "vtksys")
set(vtkDICOMParser_LIBRARIES "vtkDICOMParser")
set(vtkDICOMParser_INCLUDE_DIRS "/home/ezequiel/VTK/build/Utilities/DICOMParser;/home/ezequiel/VTK/Utilities/DICOMParser")
set(vtkDICOMParser_LIBRARY_DIRS "")
set(vtkDICOMParser_RUNTIME_LIBRARY_DIRS "/home/ezequiel/VTK/build/lib")
set(vtkDICOMParser_WRAP_HIERARCHY_FILE "")
set(vtkDICOMParser_KIT "")
set(vtkDICOMParser_EXCLUDE_FROM_WRAPPING 1)

