set(vtkexodusII_LOADED 1)
set(vtkexodusII_DEPENDS "vtknetcdf")
set(vtkexodusII_LIBRARIES "vtkexoIIc")
set(vtkexodusII_INCLUDE_DIRS "/home/ezequiel/VTK/build/ThirdParty/exodusII;/home/ezequiel/VTK/ThirdParty/exodusII")
set(vtkexodusII_LIBRARY_DIRS "")
set(vtkexodusII_RUNTIME_LIBRARY_DIRS "/home/ezequiel/VTK/build/lib")
set(vtkexodusII_WRAP_HIERARCHY_FILE "")
set(vtkexodusII_KIT "")
set(vtkexodusII_EXCLUDE_FROM_WRAPPING 1)

