set(vtkfreetype_LOADED 1)
set(vtkfreetype_DEPENDS "vtkkwiml;vtkzlib")
set(vtkfreetype_LIBRARIES "vtkfreetype")
set(vtkfreetype_INCLUDE_DIRS "/home/ezequiel/VTK/build/ThirdParty/freetype;/home/ezequiel/VTK/ThirdParty/freetype")
set(vtkfreetype_LIBRARY_DIRS "")
set(vtkfreetype_RUNTIME_LIBRARY_DIRS "/home/ezequiel/VTK/build/lib")
set(vtkfreetype_WRAP_HIERARCHY_FILE "")
set(vtkfreetype_KIT "")
set(vtkfreetype_EXCLUDE_FROM_WRAPPING 1)

