set(vtkhdf5_LOADED 1)
set(vtkhdf5_DEPENDS "vtkzlib")
set(vtkhdf5_LIBRARIES "vtkhdf5_hl;vtkhdf5")
set(vtkhdf5_INCLUDE_DIRS "/home/ezequiel/VTK/build/ThirdParty/hdf5/vtkhdf5;/home/ezequiel/VTK/ThirdParty/hdf5/vtkhdf5/hl/src;/home/ezequiel/VTK/ThirdParty/hdf5/vtkhdf5/src;/home/ezequiel/VTK/build/ThirdParty/hdf5;/home/ezequiel/VTK/ThirdParty/hdf5")
set(vtkhdf5_LIBRARY_DIRS "")
set(vtkhdf5_RUNTIME_LIBRARY_DIRS "/home/ezequiel/VTK/build/lib")
set(vtkhdf5_WRAP_HIERARCHY_FILE "")
set(vtkhdf5_KIT "")
set(vtkhdf5_EXCLUDE_FROM_WRAPPING 1)

