set(vtkMetaIO_LOADED 1)
set(vtkMetaIO_DEPENDS "vtkzlib")
set(vtkMetaIO_LIBRARIES "vtkmetaio")
set(vtkMetaIO_INCLUDE_DIRS "/home/ezequiel/VTK/build/Utilities/MetaIO/vtkmetaio;/home/ezequiel/VTK/build/Utilities/MetaIO;/home/ezequiel/VTK/Utilities/MetaIO")
set(vtkMetaIO_LIBRARY_DIRS "")
set(vtkMetaIO_RUNTIME_LIBRARY_DIRS "/home/ezequiel/VTK/build/lib")
set(vtkMetaIO_WRAP_HIERARCHY_FILE "")
set(vtkMetaIO_KIT "")
set(vtkMetaIO_EXCLUDE_FROM_WRAPPING 1)

