set(vtknetcdf_LOADED 1)
set(vtknetcdf_DEPENDS "vtkhdf5")
set(vtknetcdf_LIBRARIES "vtkNetCDF;vtkNetCDF_cxx")
set(vtknetcdf_INCLUDE_DIRS "/home/ezequiel/VTK/ThirdParty/netcdf/vtknetcdf/include;/home/ezequiel/VTK/build/ThirdParty/netcdf/vtknetcdf;/home/ezequiel/VTK/build/ThirdParty/netcdf;/home/ezequiel/VTK/ThirdParty/netcdf")
set(vtknetcdf_LIBRARY_DIRS "")
set(vtknetcdf_RUNTIME_LIBRARY_DIRS "/home/ezequiel/VTK/build/lib")
set(vtknetcdf_WRAP_HIERARCHY_FILE "")
set(vtknetcdf_KIT "")
set(vtknetcdf_EXCLUDE_FROM_WRAPPING 1)

