set(vtksqlite_LOADED 1)
set(vtksqlite_DEPENDS "")
set(vtksqlite_LIBRARIES "vtksqlite")
set(vtksqlite_INCLUDE_DIRS "/home/ezequiel/VTK/build/ThirdParty/sqlite;/home/ezequiel/VTK/ThirdParty/sqlite")
set(vtksqlite_LIBRARY_DIRS "")
set(vtksqlite_RUNTIME_LIBRARY_DIRS "/home/ezequiel/VTK/build/lib")
set(vtksqlite_WRAP_HIERARCHY_FILE "")
set(vtksqlite_KIT "")
set(vtksqlite_EXCLUDE_FROM_WRAPPING 1)

