set(vtkTestingGenericBridge_LOADED 1)
set(vtkTestingGenericBridge_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonMisc")
set(vtkTestingGenericBridge_LIBRARIES "vtkTestingGenericBridge")
set(vtkTestingGenericBridge_INCLUDE_DIRS "/home/ezequiel/VTK/build/Testing/GenericBridge;/home/ezequiel/VTK/Testing/GenericBridge")
set(vtkTestingGenericBridge_LIBRARY_DIRS "")
set(vtkTestingGenericBridge_RUNTIME_LIBRARY_DIRS "/home/ezequiel/VTK/build/lib")
set(vtkTestingGenericBridge_WRAP_HIERARCHY_FILE "")
set(vtkTestingGenericBridge_KIT "")
set(vtkTestingGenericBridge_EXCLUDE_FROM_WRAPPING 1)

