set(vtkTestingIOSQL_LOADED 1)
set(vtkTestingIOSQL_DEPENDS "vtkIOSQL")
set(vtkTestingIOSQL_LIBRARIES "vtkTestingIOSQL")
set(vtkTestingIOSQL_INCLUDE_DIRS "/home/ezequiel/VTK/build/Testing/IOSQL;/home/ezequiel/VTK/Testing/IOSQL")
set(vtkTestingIOSQL_LIBRARY_DIRS "")
set(vtkTestingIOSQL_RUNTIME_LIBRARY_DIRS "/home/ezequiel/VTK/build/lib")
set(vtkTestingIOSQL_WRAP_HIERARCHY_FILE "")
set(vtkTestingIOSQL_KIT "")
set(vtkTestingIOSQL_EXCLUDE_FROM_WRAPPING 1)

