set(vtkTestingCore_LOADED 1)
set(vtkTestingCore_DEPENDS "vtkCommonCore")
set(vtkTestingCore_LIBRARIES "vtkCommonCore")
set(vtkTestingCore_INCLUDE_DIRS "/home/ezequiel/VTK/build/Testing/Core;/home/ezequiel/VTK/Testing/Core")
set(vtkTestingCore_LIBRARY_DIRS "")
set(vtkTestingCore_RUNTIME_LIBRARY_DIRS "/home/ezequiel/VTK/build/lib")
set(vtkTestingCore_WRAP_HIERARCHY_FILE "")
set(vtkTestingCore_KIT "")
set(vtkTestingCore_EXCLUDE_FROM_WRAPPING 1)

