set(vtkzlib_LOADED 1)
set(vtkzlib_DEPENDS "")
set(vtkzlib_LIBRARIES "vtkzlib")
set(vtkzlib_INCLUDE_DIRS "/home/ezequiel/VTK/build/ThirdParty/zlib;/home/ezequiel/VTK/ThirdParty/zlib")
set(vtkzlib_LIBRARY_DIRS "")
set(vtkzlib_RUNTIME_LIBRARY_DIRS "/home/ezequiel/VTK/build/lib")
set(vtkzlib_WRAP_HIERARCHY_FILE "")
set(vtkzlib_KIT "")
set(vtkzlib_EXCLUDE_FROM_WRAPPING 1)

